const body = document.body;
const notice = document.querySelector('.notice');
const messages = { importing:['Importing attachment: release-evidence.pdf · 62%', 'normal'], oversize:['Attachment rejected: 54 MB exceeds the 25 MB meeting limit.', 'error'], generating:['Generating Quality Control summary. No provider call is being made.', 'normal'], success:['Summary generated and added to the shared artifact.', 'normal'], failure:['OpenAI could not complete the request. Check provider status before trying again.', 'error'], unknown:['Outcome unknown: the request may have reached the provider. It will not be replayed automatically.', 'warning'], cancelled:['Generation cancelled. No further action was taken.', 'normal'] };
function showNotice(text, kind = 'normal') { notice.textContent = text; notice.dataset.kind = kind; notice.hidden = false; }
function setState(state) { body.dataset.state = state; const message = messages[state]; if (message) showNotice(...message); else notice.hidden = true; }
document.querySelector('#scenario').addEventListener('change', (event) => setState(event.target.value));
document.querySelectorAll('[data-view-button]').forEach((button) => button.addEventListener('click', () => { const view = button.dataset.viewButton; body.dataset.view = view; document.querySelectorAll('.view').forEach((panel) => panel.hidden = panel.dataset.view !== view); document.querySelectorAll('.stepper [data-view-button]').forEach((item) => item.classList.toggle('active', item.dataset.viewButton === view)); }));
document.querySelectorAll('[data-open-dialog]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.openDialog).showModal()));
document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'generate') setState('generating'); if (action === 'success') setState('success'); if (action === 'import') setState('importing'); if (action === 'message') showNotice('Guidance added to the local demo transcript.'); }));
document.querySelectorAll('dialog').forEach((dialog) => dialog.addEventListener('close', () => { if (dialog.id === 'create' && dialog.returnValue === 'default') { setState('new'); body.dataset.view = 'meeting'; document.querySelectorAll('.view').forEach((panel) => panel.hidden = panel.dataset.view !== 'meeting'); showNotice('New meeting table created with fake data.'); } }));
