const body = document.body;
const notice = document.querySelector('.notice');
const messages = document.querySelector('#messages');
const seatGrid = document.querySelector('#seat-grid');
const artifactList = document.querySelector('#artifact-list');
const sessionControl = document.querySelector('#session-control');
const sessionLabel = document.querySelector('#session-label');
const sessionIcon = document.querySelector('#session-icon path');
const runStatus = document.querySelector('#run-status');
const saved = JSON.parse(sessionStorage.getItem('aimt-preferred-concept') || '{}');
let seats = [
  { id: 'mira', name: 'Mira', role: 'Lead Quality Control', provider: 'OpenAI', model: 'GPT-5.6 Terra', effort: 'Deep', color: '#49bd99' },
  { id: 'ravi', name: 'Ravi', role: 'Lead Executioner', provider: 'Gemini', model: 'Gemini 2.5', effort: 'Balanced', color: '#75a8d5' },
  { id: 'jordan', name: 'Jordan', role: 'Final Decision Maker', provider: 'Anthropic', model: 'Claude Opus', effort: 'Deep', color: '#f0b458' },
  { id: 'you', name: 'You', role: 'Meeting owner', provider: 'Local', model: 'Operator message', effort: 'Auto', color: '#b780d4' }
];
const transcript = [
  ['you', '10:14:05', 'Use the release checklist as the acceptance baseline.'],
  ['mira', '10:14:12', 'The attachment shows a recoverable import failure, but the request timeout needs a clear outcome-unknown message.'],
  ['ravi', '10:14:24', 'Proposed wording prevents an automatic replay when the provider may have accepted the request.'],
  ['jordan', '10:14:41', 'Decision pending: attach the final acceptance evidence and I will rule.']
];
let artifacts = [
  { type: 'Summary', title: 'Quality Control summary', meta: 'Quality Control · Round 2 · 10:14', content: 'Conditional proceed. Verify the recovery message and attachment-size boundary before Present.' },
  { type: 'Decision', title: 'Final ruling draft', meta: 'Present · pending evidence', content: 'FINAL_RULING: pending attachment evidence.' },
  { type: 'Artifact', title: 'Release checklist notes', meta: 'Execution · Round 2', content: 'Acceptance evidence is attached to the meeting table and available to the selected provider.' }
];
function notify(text, kind = 'normal') { notice.textContent = text; notice.dataset.kind = kind; notice.hidden = false; }
function seat(id) { return seats.find((item) => item.id === id); }
function element(tag, text, className) { const item = document.createElement(tag); if (text) item.textContent = text; if (className) item.className = className; return item; }
function renderTranscript() { messages.replaceChildren(); transcript.forEach(([id, time, text]) => { const person = seat(id); const article = element('article', '', `message${id === 'you' ? ' operator' : ''}`); article.style.setProperty('--seat-color', person.color); const header = element('div', '', 'message-header'); const identity = element('div'); identity.append(element('strong', person.name), element('small', person.role)); const meta = element('div', '', 'meta'); meta.append(element('time', time), element('small', person.model)); header.append(identity, meta); article.append(header, element('p', text)); messages.append(article); }); }
function openSeat(id) { const person = id ? seat(id) : { id: '', name: '', role: 'Participant', provider: 'OpenAI', model: 'GPT-5.6 Terra', effort: 'Auto', color: '#49bd99' }; document.querySelector('#seat-dialog-title').textContent = id ? `Configure ${person.name}` : 'Add seat'; ['id', 'name', 'role', 'provider', 'model', 'effort', 'color'].forEach((key) => { document.querySelector(`#seat-${key}`).value = person[key]; }); document.querySelector('#seat-dialog').showModal(); }
function renderSeats() { seatGrid.replaceChildren(); seats.filter((item) => item.id !== 'you').forEach((person) => { const button = element('button', '', 'seat-card'); button.style.setProperty('--seat-color', person.color); button.dataset.seat = person.id; button.setAttribute('aria-label', `Configure seat ${person.name}`); button.append(element('b', person.name), element('small', person.role), element('small', `${person.provider} · ${person.model}`)); seatGrid.append(button); }); const add = element('button', 'Add Seat', 'seat-card add-seat'); add.dataset.action = 'add-seat'; add.setAttribute('aria-label', 'Add seat'); seatGrid.append(add); }
function renderArtifacts() { artifactList.replaceChildren(); if (!artifacts.length) { artifactList.append(element('p', 'No generated artifacts yet. Start the table or request one here.', 'artifact-empty')); return; } artifacts.forEach((artifact, index) => { const button = element('button', '', 'artifact-row'); button.dataset.artifact = index; button.append(element('b', artifact.title), element('small', `${artifact.type} · ${artifact.meta}`)); artifactList.append(button); }); }
function setSession(state) { body.dataset.session = state; const labels = { never: ['Start', 'Start session', 'Not started', 'M8 5v14l11-7z'], running: ['Pause', 'Pause session', 'Running', 'M6 5h4v14H6zm8 0h4v14h-4z'], paused: ['Continue', 'Continue session', 'Paused', 'M7 4v7h7M7 11a7 7 0 1 0 2-5'] }; const [label, accessible, status, icon] = labels[state]; sessionLabel.textContent = label; sessionIcon.setAttribute('d', icon); sessionControl.setAttribute('aria-label', accessible); runStatus.textContent = status; }
function applyAppearance(value) { body.dataset.appearance = value === 'system' ? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : value; body.dataset.preference = value; }
function setAppearance(key, value) { if (key === 'appearance') applyAppearance(value); else body.dataset[key] = value; Object.assign(saved, { appearance: body.dataset.preference || body.dataset.appearance, theme: body.dataset.theme, font: body.dataset.font }); sessionStorage.setItem('aimt-preferred-concept', JSON.stringify(saved)); }
function setOperation(value) { document.querySelector('.empty-state').hidden = value !== 'empty'; document.querySelector('.session-content').hidden = value === 'empty'; const copy = { importing: ['Importing attachment: release-evidence.pdf · 62%.', 'normal'], oversize: ['Attachment rejected: 54 MB exceeds the fixed 25 MB limit.', 'error'], generating: ['Generating an artifact locally. No provider request is made.', 'normal'], success: ['Artifact generation confirmed and added to the panel.', 'normal'], failure: ['Definite provider failure: the request was rejected before generation.', 'error'], unknown: ['Outcome unknown: the request may have reached the provider. Automatic replay is disabled.', 'warning'], cancelled: ['Operation cancelled. The table is unchanged.', 'normal'] }; if (copy[value]) notify(...copy[value]); else notice.hidden = true; }
function openArtifact(index) { const artifact = artifacts[index]; document.querySelector('#artifact-type').textContent = artifact.type; document.querySelector('#artifact-title').textContent = artifact.title; document.querySelector('#artifact-meta').textContent = artifact.meta; document.querySelector('#artifact-content').textContent = artifact.content; document.querySelector('#artifact-dialog').showModal(); }
document.querySelectorAll('[data-dialog]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.dialog).showModal()));
document.querySelector('#operation-state').addEventListener('change', (event) => setOperation(event.target.value));
document.querySelectorAll('[data-page-button]').forEach((button) => button.addEventListener('click', () => { const page = button.dataset.pageButton; body.dataset.page = page; document.querySelectorAll('.page').forEach((item) => item.hidden = item.id !== page); document.querySelectorAll('.main-nav button').forEach((item) => item.classList.toggle('active', item.dataset.pageButton === page)); }));
sessionControl.addEventListener('click', () => { setSession(body.dataset.session === 'never' ? 'running' : body.dataset.session === 'running' ? 'paused' : 'running'); });
document.querySelector('#seat-grid').addEventListener('click', (event) => { const button = event.target.closest('button'); if (!button) return; openSeat(button.dataset.action === 'add-seat' ? '' : button.dataset.seat); });
document.querySelector('#seat-form').addEventListener('submit', () => { const id = document.querySelector('#seat-id').value || `seat-${Date.now()}`; const data = Object.fromEntries(['id', 'name', 'role', 'provider', 'model', 'effort', 'color'].map((key) => [key, document.querySelector(`#seat-${key}`).value])); data.id = id; const index = seats.findIndex((item) => item.id === id); if (index >= 0) seats[index] = data; else seats.push(data); renderSeats(); renderTranscript(); notify(`${data.name || 'Seat'} saved. Transcript accents updated.`); });
document.querySelector('#artifact-list').addEventListener('click', (event) => { const button = event.target.closest('button'); if (button) openArtifact(Number(button.dataset.artifact)); });
document.querySelectorAll('[data-settings-page]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-settings-section]').forEach((section) => section.hidden = section.dataset.settingsSection !== button.dataset.settingsPage); document.querySelectorAll('[data-settings-page]').forEach((item) => item.classList.toggle('active', item === button)); saved.settingsSection = button.dataset.settingsPage; sessionStorage.setItem('aimt-preferred-concept', JSON.stringify(saved)); }));
document.querySelectorAll('#appearance-select,#theme-select,#font-select').forEach((select) => select.addEventListener('change', () => setAppearance(select.id.replace('-select', ''), select.value)));
document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'copy') notify('Full transcript copied in this local demonstration.'); if (action === 'send') notify('Guidance queued for the next phase.'); if (action === 'stop') { setSession('never'); notify('Session stopped.'); } if (action === 'import') setOperation('importing'); if (action === 'generate-artifact') { artifacts.unshift({ type: 'Summary', title: 'Generated Quality Control summary', meta: 'Just now · confirmed', content: 'Generated locally for this prototype. No provider request was made.' }); renderArtifacts(); document.querySelector('#generation-progress').value = 100; document.querySelector('#generation-status').textContent = 'Confirmed'; notify('Artifact generated successfully.'); } if (action === 'toggle-artifacts') { artifacts = artifacts.length ? [] : [{ type: 'Summary', title: 'Quality Control summary', meta: 'Quality Control · Round 2', content: 'Conditional proceed.' }]; button.textContent = artifacts.length ? 'Show empty' : 'Show populated'; renderArtifacts(); } if (action === 'add-seat') openSeat(''); if (action === 'reveal-key') { const input = button.parentElement.querySelector('input'); input.type = input.type === 'password' ? 'text' : 'password'; button.textContent = input.type === 'password' ? 'Show' : 'Hide'; } if (action === 'save-key') { button.closest('fieldset').querySelector('.provider-state').textContent = 'Fake value saved for this browser session'; notify('Fake provider key updated locally.'); } if (action === 'clear-key') { const fieldset = button.closest('fieldset'); fieldset.querySelector('input').value = ''; fieldset.querySelector('.provider-state').textContent = 'No key saved'; notify('Fake provider key cleared locally.'); } if (action === 'refresh-models') { document.querySelector('#model-status').textContent = 'Model refresh demonstrated. No network request was made.'; } if (action === 'save-limits') { const get = (name) => Number(document.querySelector(`[name="${name}"]`).value); const bad = get('phaseTokens') <= 0 || get('totalTokens') <= 0 || get('cost') <= 0 || get('rounds') <= 0 || get('loops') <= 0 || get('phaseSeconds') <= 0 || get('sessionSeconds') <= 0; const error = bad ? 'All hard-stop limits must be positive values.' : get('totalTokens') < get('phaseTokens') ? 'Maximum total tokens must be at least the per-phase token limit.' : get('sessionSeconds') < get('phaseSeconds') ? 'Maximum session seconds must be at least the per-phase time limit.' : ''; document.querySelector('#limit-error').textContent = error; if (!error) notify('Hard-stop values validated in this demonstration.'); } }));
if (saved.appearance) { applyAppearance(saved.appearance); body.dataset.theme = saved.theme; body.dataset.font = saved.font; ['appearance', 'theme', 'font'].forEach((key) => { document.querySelector(`#${key}-select`).value = saved[key]; }); }
(document.querySelector(`[data-settings-page="${saved.settingsSection}"]`) || document.querySelector('[data-settings-page="providers"]')).click();
renderSeats(); renderTranscript(); renderArtifacts(); setSession('never');
